### ISSUE TITLE
Social media-specific image in meta tags

### ISSUE THREAD

**Issue by codex-press** [codex-press/app#1]
We need a way to show a different image when people share a story. Currently, the first image or the first frame of the first video is passed to Twitter and Facebook when the story is shared. This can be overridden by adding the class `.cover` to a different image. However, this image also travels to index pages, like the Coda homepage. We need a way to have a different image appear just on social media.

The proposed enhancement is adding the class `.social-cover` for the image that should be shared in social media but not used for index pages.

Thanks, Katia!

**Comment by twfarnam** [comment]
This now works. You can add .social-cover to the image you want to be used in social media tags.
