### ISSUE TITLE
Can't delete HTML block in codex

### ISSUE THREAD

**Issue by panoptical** [codex-press/app#13]
I have some HTML blocks in a couple of pages that we no longer need but I can't seem to delete them.  I've made them ".hidden" and stuck them at the bottom of the page for now.

https://codex.press/edit/article/coda/disinformation-crisis
https://codex.press/edit/article/coda/migration-crisis

**Comment by twfarnam** [comment]
Hey, you should be able to right click on the part where the numbers are

**Comment by panoptical** [comment]
Got it, thanks
