### ISSUE TITLE
Adding new metadata fields is buggy

### ISSUE THREAD

**Issue by panoptical** [codex-press/app#2]
I have an article with one existing added metadata field (current).  I can add a new field which is called new_field but when I try to rename it (tried in Chrome and Firefox) the rename doesn't persist after saving (for example, if I save, then refresh, the rename disappears).

Also, when I try to add another additional field, it doesn't let me.

**Comment by twfarnam** [comment]
Yes, just discovered this one today myself. It's very annoying and totally essential for Coda.

**Comment by codex-press** [comment]
fixed!
