### ISSUE TITLE
CTRL+click in Chrome on Windows opens page that won't load

### ISSUE THREAD

**Issue by panoptical** [codex-press/app#5]
When I use CTRL+click to open a link in a new tab in Chrome on Windows the new tab shows me the loading screen and never actually loads the page.

**Comment by twfarnam** [comment]
This is an issue with the iframe sandbox carrying over to the new tab. We can fix it by adding rel="noopener" attribute to the links. I will investigate

**Comment by twfarnam** [comment]
This should be fixed now. I needed to add allow-popups-to-escape-sandbox on the sandbox. More info here:

https://wiki.whatwg.org/wiki/Iframe_sandbox_improvments
https://www.chromestatus.com/feature/5708368589094912
https://googlechrome.github.io/samples/allow-popups-to-escape-sandbox/index.html

Thanks for flagging, Neal
